### ISSUE TITLE
example fails on Intel Edison with Xadow Edison wearable

### ISSUE THREAD

**Issue by Jcbobo** [mrkrasser/node-red-contrib-bmp085#7]
I just start using my new intel Edison, I flash it to the latest firmware version, and install node-red.
node version v0.10.38
node-red version 0.13.1

 I'm trying to make the  [GlowingThermometer example](https://github.com/Seeed-Studio/Xadow_Edison_Demos)  with node-red (the original example is working correctly) starting from access the [BMP180(http://www.seeedstudio.com/wiki/Xadow_-_Barometer_BMP180) data.
As soon I deploy the example of using the node-red-contrib-bmp085 abstraction the flow stops with this error.

`[info] Starting flows
[  496.167075] i2c-designware-pci 0000:00:08.1: i2c_dw_handle_tx_abort: lost arb                      itration
19 Jun 05:41:29 - [info] Started flows
19 Jun 05:41:29 - [red] Uncaught Exception:
19 Jun 05:41:29 - Error: Error reading length of bytes
    at i2c.readBytes (/home/root/node-red-0.13.1/node_modules/node-red-contrib-b                      mp085/node_modules/bmp085/node_modules/i2c/lib/i2c.coffee:130:19)
    at BMP085.readWord (/home/root/node-red-0.13.1/node_modules/node-red-contrib-bmp085/node_modules/bmp085/bmp085.js:131:15)
    at /home/root/node-red-0.13.1/node_modules/node-red-contrib-bmp085/node_modu                      les/bmp085/bmp085.js:156:14
    at Array.forEach (native)
    at BMP085.calibrate (/home/root/node-red-0.13.1/node_modules/node-red-contri                      b-bmp085/node_modules/bmp085/bmp085.js:155:31)
    at BMP085.read (/home/root/node-red-0.13.1/node_modules/node-red-contrib-bmp                      085/node_modules/bmp085/bmp085.js:280:10)
    at getData (/home/root/node-red-0.13.1/node_modules/node-red-contrib-bmp085/                      73-bmp085.js:60:11)
    at new bmp085_Node (/home/root/node-red-0.13.1/node_modules/node-red-contrib                      -bmp085/73-bmp085.js:74:3)
    at createNode (/home/root/node-red-0.13.1/red/runtime/nodes/flows/Flow.js:27                      6:18)
    at Flow.start (/home/root/node-red-0.13.1/red/runtime/nodes/flows/Flow.js:64                      :35)
root@edison:~/node-red-0.13.1`

I check the I2c device ( /dev/i2c-1 and i think is the correct one) also for the periferal register.
Is this abstraction working only with the Arduino expansio board?

**Comment by microspace** [comment]
Same error here
